version: '3.8'

services:
  ai-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ai-network

  # Optional: Development service
  ai-dev:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npm install -g pnpm &&
             pnpm install &&
             pnpm dev --host 0.0.0.0"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - ai-network
    profiles:
      - dev

networks:
  ai-network:
    driver: bridge 